version: '3' # версия синтаксиса
services:
 express-app: # Сервер Express
    build: .
    container_name: server
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'mongodb://monty:pass@db:27017/mydatabase?authSource=admin&directConnection=true'
 db: # База данных
    container_name: database
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: monty
      MONGO_INITDB_ROOT_PASSWORD: pass

